#
# This Dockerfile is used when install a standard package of Linux distribution
#
FROM d-base-image:v1.0.0

ARG APPLICATION_DOWNLOADED_FILE_NAME

RUN apt-get update && \
    apt-get install -y $APPLICATION_DOWNLOADED_FILE_NAME && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
