APPLICATION_DOWNLOADED_FILE_NAME='bash'
APPLICATION_URL=""
APPLICATION_IMAGE_DOCKER="run-bash:d-sh-test-latest-application-interactive"
APPLICATION_DEPENDENCIES="bash"
APPLICATION_COMMAND_LINE="/bin/bash"
APPLICATION_INTERACTIVE="true"
